# Generated by Django 5.2.18 on 2026-10-09 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('slug', models.SlugField(blank=True, max_length=180, unique=True)),
                ('short_description', models.CharField(max_length=300)),
                ('full_description', models.TextField(blank=True)),
                ('tech_stack', models.JSONField(blank=True, default=list, help_text='List of technology names')),
                ('features', models.JSONField(blank=True, default=list, help_text='List of feature strings')),
                ('architecture', models.JSONField(blank=True, default=list, help_text='List of flows: [{"title": "...", "steps": ["...", "..."]}]')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('github_url', models.URLField(blank=True)),
                ('live_url', models.URLField(blank=True)),
                ('featured', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
